### PR TITLE
Changed gradient sig to move gradient first.

### PR DESCRIPTION
**Pull request by btracey**
The convention is to put receivers first, and allocate if nil. Previously, Gradient had not followed this convention. This moves the []float64 receiver to be the first argument, allocates it if nil, and returns the value from the function. This brings it into convention with the other packages. This PR also adds a test for the nil case.

### CODE REVIEW

**Comment by btracey** [comment]
@jonlawlor, both for the change and for the travis failure.

**Comment by btracey** [comment]
Is travis pointed to this directory appropriately?

**Comment by jonlawlor** [comment]
It looks like this branch is 22 behind master.

**Comment by btracey** [comment]
Oh, Sorry. That explains the "missing travis file". My bad.

**Comment by btracey** [comment]
Okay. Sorry for that.

PTAL @jonlawlor

**Comment by jonlawlor** [comment]
LGTM

**Pull request merged**
